### ISSUE TITLE
lots map

### ISSUE THREAD

**Issue by Joyykim** [Joyykim/modu_parking_api#20]
GET /lots/map(action) 
: 주차장 맵뷰역(예: 서울시)
1. 주차장과의 거리계산(주어진 위도, 경도 기준), 정렬
2. 줌레벨로 범위 필터링 - 3단계 (1, 3, 5km)
3. 주차장 정보 리턴(basic_rate, lat, lng, id)
4. 검색 조건(ex:partnership) 필터링 추후 적용 
RES-basic_rate, lat, lng, id

**Comment by Jamie-Cheon** [comment]
jamie did
