### ISSUE TITLE
parkings create

### ISSUE THREAD

**Issue by Joyykim** [Joyykim/modu_parking_api#24]
POST   /parkings/	    
: 주차 이벤트 생성(주인의 사용내역만)
: 과거 주차내역 list으로 시간, 가격, 주차장이름 나열
REQ-start_time, parking_time, lot(foreign),
RES-total_fee(lot.basic + (lot.additionalRate * (parking_time - t)), start_time, parking_time, lot(foreign), end_time(계산해야함)

**Comment by Jamie-Cheon** [comment]
Jamie did
